services:
  runner:
    image: ghcr.io/schms27/gh-self-hosted-runner:latest #youssefbrr/github-actions:latest # You can use this image or build your own
    restart: always
    environment:
      - REPO=schms27/hamstr
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=gh-runner-n
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - go-mod-cache:/home/docker/go/pkg/mod
      - go-build-cache:/home/docker/.cache/go-build
    deploy:
      mode: replicated
      replicas: 1
      #resources:
      #  limits:
      #    cpus: '0.75'
      #    memory: 2048M
      #  reservations:
      #    cpus: '0.4'
      #    memory: 256M
volumes:
  go-mod-cache:
  go-build-cache:
