version: '3.8'

services:
  runner:
    build: ./Docker Image
    restart: always
    environment:
      - REPO=<owner>/<repo>
      - REG_TOKEN=<reg-token-for-self-hosted-runner>
      - NAME=<runner-name>
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.4'
          memory: 256M